# Openclashä½¿ç”¨ï¼Œæ­é…ç»•è¿‡å¤§é™†
# å®ˆå€™è‡ªç”¨
# æœºåœºè®¢é˜…ï¼Œè®¢é˜…1,è®¢é˜…2 å¯ä»¥è‡ªå®šåå­—

proxy-providers:
  è®¢é˜…1:
    type: http
    interval: 86400
    path: ./proxy_provider/Providers1.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
    proxy: DIRECT
    url: "è®¢é˜…é“¾æ¥1"
    override:
      additional-prefix: "[æœºåœºåç§°1]"
      skip-cert-verify: true  # ç»•è¿‡è¯ä¹¦éªŒè¯
      udp: true # å¼€å¯udp
  è®¢é˜…2:
    type: http
    interval: 86400
    path: ./proxy_provider/Providers2.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
    proxy: DIRECT
    url: "è®¢é˜…é“¾æ¥1"
    override:
      additional-prefix: "[æœºåœºåç§°1]"
      skip-cert-verify: true  # ç»•è¿‡è¯ä¹¦éªŒè¯
      udp: true # å¼€å¯udp
      
# ç”¨äºä¸‹è½½è®¢é˜…æ—¶æŒ‡å®šUA
global-ua: clash.meta
    
# å…¨å±€é…ç½®
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
ipv6: false
allow-lan: true      # å±€åŸŸç½‘è¿æ¥ï¼šå…è®¸å…¶ä»–è®¾å¤‡ç»è¿‡æœ¬æœºä»£ç†
unified-delay: true   # ç»Ÿä¸€å»¶è¿Ÿï¼šç»Ÿä¸€æ˜¾ç¤ºèŠ‚ç‚¹å»¶è¿Ÿ
tcp-concurrent: true    # TCPå¹¶å‘ï¼šå…è®¸å¹¶å‘è¿æ¥TCP,æé«˜å¹¶å‘æ€§èƒ½
# interface-name: eth0  ï¼ˆè·¯ç”±å™¨ä¸‹æ ¹æ®æƒ…å†µæŒ‡å®šå‡ºç«™æ¥å£ï¼‰
authentication:
#  - name:passwd
  
geodata-mode: false   # GEOæ¨¡å¼ï¼štrueä½¿ç”¨geoip.datæ•°æ®åº“,falseä½¿ç”¨mmdbæ•°æ®åº“
# GEO æ–‡ä»¶åŠ è½½æ¨¡å¼ï¼ˆstandardï¼šæ ‡å‡†åŠ è½½å™¨/memconservativeï¼šä¸“ä¸ºå†…å­˜å—é™ (å°å†…å­˜) è®¾å¤‡ä¼˜åŒ–çš„åŠ è½½å™¨ (é»˜è®¤å€¼)ï¼‰
geodata-loader: standard
geo-auto-update: true  # æ˜¯å¦è‡ªåŠ¨æ›´æ–° geodata
geo-update-interval: 48  # æ›´æ–°é—´éš”ï¼Œå•ä½ï¼šå°æ—¶
geox-url:
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb"
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  asn: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
  
# æ§åˆ¶é¢æ¿
external-controller: 0.0.0.0:9090  # RESTful API ç›‘å¬åœ°å€
# secret: ""
# external-ui: ui
# external-ui-url: "https://github.com/Zephyruso/zashboard/archive/gh-pages.zip"
# ä¸‹è½½é¢æ¿åœ°å€å¯æ›´æ¢ï¼šhttps://github.com/MetaCubeX/metacubexd/archive/gh-pages.zip

# åŒ¹é…è¿›ç¨‹ always/strict/off
find-process-mode: strict
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 30

# ç­–ç•¥ç»„é€‰æ‹©å’Œfakeipç¼“å­˜
profile:
  store-selected: true
  store-fake-ip: true
  
# æµé‡å—…æ¢
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.push.apple.com"
    - "+.apple.com"
    - '+.wechat.com'
    - '+.qpic.cn'
    - '+.qq.com'
    - '+.wechatapp.com'
    
# ä»£ç†æ¨¡å¼
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  
# DNSæ¨¡å—
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  prefer-h3: true # æ˜¯å¦å¼€å¯ DoH æ”¯æŒ HTTP/3ï¼Œå°†å¹¶å‘å°è¯•
  respect-rules: true
  # æ¨¡å¼åˆ‡æ¢ redir-host / fake-ip
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  # æ¨¡å¼åˆ‡æ¢ whitelist/blacklist 
  # é»‘åå•æ¨¡å¼è¡¨ç¤ºå¦‚æœåŒ¹é…æˆåŠŸåˆ™ä¸è¿”å› Fake-IP, ç™½åå•æ¨¡å¼æ—¶åªæœ‰åŒ¹é…æˆåŠŸæ‰è¿”å› Fake-IP
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:Lan_domain,Custom_Direct,Direct_domain,XiaoMi_domain,IPTVMainland_domain,Download_domain"
    - "+.services.googleapis.cn"
    - "+.xn--ngstr-lra8j.com"
    - "time.*.com"
    - "+.pool.ntp.org"
    - "+.ntp.tencent.com"
    - "+.ntp1.aliyun.com"
    - "+.ntp.ntsc.ac.cn"
    - "+.cn.ntp.org.cn"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29


# ç­–ç•¥ç»„é”šç‚¹
pr1: &pr1 {type: select, proxies: [DIRECT, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯ä½å€ç‡, ğŸ‡¯ğŸ‡µ æ—¥æœ¬ä½å€ç‡, ğŸ‡ºğŸ‡¸ ç¾å›½ä½å€ç‡, ğŸ‡¨ğŸ‡³ å°æ¹¾ä½å€ç‡, ğŸ‡¸ğŸ‡¬ ç‹®åŸä½å€ç‡, ğŸš€ æ‰‹åŠ¨åˆ‡æ¢]}
pr2: &pr2 {type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯ä½å€ç‡, ğŸ‡¯ğŸ‡µ æ—¥æœ¬ä½å€ç‡, ğŸ‡ºğŸ‡¸ ç¾å›½ä½å€ç‡, ğŸ‡¨ğŸ‡³ å°æ¹¾ä½å€ç‡, ğŸ‡¸ğŸ‡¬ ç‹®åŸä½å€ç‡, ğŸš€ æ‰‹åŠ¨åˆ‡æ¢, DIRECT]}

# ä»£ç†ç»„é”šç‚¹
UrlTest: &UrlTest {type: url-test, interval: 300, tolerance: 20, url: 'http://www.gstatic.com/generate_204', disable-udp: false, timeout: 2000, max-failed-times: 3, include-all-providers: true}
FallBack: &FallBack {type: fallback, interval: 300, lazy: true, url: 'http://www.gstatic.com/generate_204', disable-udp: false, timeout: 2000, max-failed-times: 3, include-all-providers: true}
LoadBalance: &LoadBalance {type: load-balance, interval: 300, lazy: true, url: 'http://www.gstatic.com/generate_204', disable-udp: false, strategy: consistent-hashing, timeout: 2000, max-failed-times: 3, include-all-providers: true}

# ç­–ç•¥ç»„
proxy-groups:
  - {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ”¯ æ•…éšœè½¬ç§», ğŸ”® è´Ÿè½½å‡è¡¡, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯ä½å€ç‡, ğŸ‡¯ğŸ‡µ æ—¥æœ¬ä½å€ç‡, ğŸ‡ºğŸ‡¸ ç¾å›½ä½å€ç‡, ğŸ‡¨ğŸ‡³ å°æ¹¾ä½å€ç‡, ğŸ‡¸ğŸ‡¬ ç‹®åŸä½å€ç‡, ğŸ‡­ğŸ‡° é¦™æ¸¯é«˜å€ç‡, ğŸ‡¯ğŸ‡µ æ—¥æœ¬é«˜å€ç‡, ğŸ‡ºğŸ‡¸ ç¾å›½é«˜å€ç‡, ğŸ‡¨ğŸ‡³ å°æ¹¾é«˜å€ç‡, ğŸ‡¸ğŸ‡¬ ç‹®åŸé«˜å€ç‡, ğŸš€ æ‰‹åŠ¨åˆ‡æ¢, DIRECT]}
  - {name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢, type: select, include-all: true}
  - {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, <<: *UrlTest}
  - {name: ğŸ”¯ æ•…éšœè½¬ç§», <<: *FallBack}
  - {name: ğŸ”® è´Ÿè½½å‡è¡¡, <<: *LoadBalance}
  - {name: ğŸ“º Embyå½±é™¢, <<: *pr2}
  - {name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯, <<: *pr2}
  - {name: ğŸ’¬ OpenAi, <<: *pr2}
  - {name: ğŸ“¹ æ²¹ç®¡è§†é¢‘, <<: *pr2}
  - {name: ğŸ¥ å¥ˆé£è§†é¢‘, <<: *pr2}
  - {name: ğŸ“º å·´å“ˆå§†ç‰¹, type: select, proxies: [ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¨ğŸ‡³ å°æ¹¾ä½å€ç‡, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸš€ æ‰‹åŠ¨åˆ‡æ¢, DIRECT]}
  - {name: ğŸ“º å“”å“©å“”å“©, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¨ğŸ‡³ å°æ¹¾ä½å€ç‡, ğŸ‡­ğŸ‡° é¦™æ¸¯ä½å€ç‡]}
  - {name: ğŸŒ å›½å¤–åª’ä½“, <<: *pr2}
  - {name: ğŸŒ å›½å†…åª’ä½“, type: select, proxies: [DIRECT, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯ä½å€ç‡, ğŸ‡¯ğŸ‡µ æ—¥æœ¬ä½å€ç‡, ğŸ‡¸ğŸ‡¬ ç‹®åŸä½å€ç‡, ğŸš€ æ‰‹åŠ¨åˆ‡æ¢]}
  - {name: ğŸ“¢ è°·æ­ŒFCM, <<: *pr1}
  - {name: â“‚ï¸ å¾®è½¯Bing, <<: *pr1}
  - {name: â“‚ï¸ å¾®è½¯äº‘ç›˜, <<: *pr1}
  - {name: â“‚ï¸ å¾®è½¯æœåŠ¡, <<: *pr1}
  - {name: ğŸ è‹¹æœæœåŠ¡, <<: *pr1}
  - {name: ğŸ® æ¸¸æˆå¹³å°, <<: *pr1}
  - {name: ğŸ¯ å…¨çƒç›´è¿, type: select, proxies: [DIRECT, ğŸš€ æ‰‹åŠ¨åˆ‡æ¢, â™»ï¸ è‡ªåŠ¨é€‰æ‹©]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, <<: *pr2}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, <<: *UrlTest, filter: "(?i)(æ¸¯|HK|hk|Hong Kong|HongKong|hongkong)(?!.*2\\.00x)"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, <<: *UrlTest, filter: "(?i)(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan)(?!.*2\\.00x)"}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, <<: *UrlTest, filter: "(?i)(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)(?!.*2\\.00x)"}
  - {name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, <<: *UrlTest, filter: "(?i)(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)(?!.*2\\.00x)"}
  - {name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, <<: *UrlTest, filter: "(?i)(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)(?!.*2\\.00x)"}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, <<: *UrlTest, filter: "(?i)(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)(?!.*2\\.00x)"}

  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯ä½å€ç‡, <<: *UrlTest, filter: "(?i)(æ¸¯|HK|hk|Hong Kong|HongKong|hongkong)(?=.*0\\.20x)"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ä½å€ç‡, <<: *UrlTest, filter: "(?i)(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan)(?=.*0\\.20x)"}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½ä½å€ç‡, <<: *UrlTest, filter: "(?i)(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)(?=.*0\\.20x)"}
  - {name: ğŸ‡¨ğŸ‡³ å°æ¹¾ä½å€ç‡, <<: *UrlTest, filter: "(?i)(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)(?=.*0\\.20x)"}
  - {name: ğŸ‡¸ğŸ‡¬ ç‹®åŸä½å€ç‡, <<: *UrlTest, filter: "(?i)(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)(?=.*0\\.20x)"}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½ä½å€ç‡, <<: *UrlTest, filter: "(?i)(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)(?=.*0\\.20x)"}

  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯é«˜å€ç‡, <<: *UrlTest, filter: "(?i)(æ¸¯|HK|hk|Hong Kong|HongKong|hongkong)(?=.*2\\.00x)"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬é«˜å€ç‡, <<: *UrlTest, filter: "(?i)(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan)(?=.*2\\.00x)"}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½é«˜å€ç‡, <<: *UrlTest, filter: "(?i)(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)(?=.*2\\.00x)"}
  - {name: ğŸ‡¨ğŸ‡³ å°æ¹¾é«˜å€ç‡, <<: *UrlTest, filter: "(?i)(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)(?=.*2\\.00x)"}
  - {name: ğŸ‡¸ğŸ‡¬ ç‹®åŸé«˜å€ç‡, <<: *UrlTest, filter: "(?i)(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)(?=.*2\\.00x)"}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½é«˜å€ç‡, <<: *UrlTest, filter: "(?i)(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)(?=.*2\\.00x)"}
rules: 
  - RULE-SET,Lan_domain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Lan_ip,ğŸ¯ å…¨çƒç›´è¿,no-resolve
  - RULE-SET,Custom_Direct,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Custom_Proxy,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,Direct_domain,ğŸ¯ å…¨çƒç›´è¿
  - GEOSITE,google-cn,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,GoogleCNProxyIP,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - GEOSITE,category-games@cn,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Steam_CDN,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,Game_Download_CDN,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - GEOSITE,category-public-tracker,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Telegram_domain,ğŸ“² ç”µæŠ¥æ¶ˆæ¯
  - RULE-SET,Telegram_ip,ğŸ“² ç”µæŠ¥æ¶ˆæ¯,no-resolve
  - RULE-SET,OpenAI_domain,ğŸ’¬ OpenAi
  - RULE-SET,OpenAI_ip,ğŸ’¬ OpenAi,no-resolve
  - RULE-SET,YouTube_domain,ğŸ“¹ æ²¹ç®¡è§†é¢‘
  - RULE-SET,YouTube_ip,ğŸ“¹ æ²¹ç®¡è§†é¢‘,no-resolve
  - RULE-SET,Apple_domain,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,Apple_ip,ğŸ è‹¹æœæœåŠ¡,no-resolve
  - RULE-SET,Bing_domain,â“‚ï¸ å¾®è½¯Bing
  - RULE-SET,OneDrive_domain,â“‚ï¸ å¾®è½¯äº‘ç›˜
  - RULE-SET,Microsoft_domain,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,XiaoMi_domain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,XiaoMi_ip,ğŸ¯ å…¨çƒç›´è¿,no-resolve
  - RULE-SET,GoogleFCM_domain,ğŸ“¢ è°·æ­ŒFCM
  - RULE-SET,GoogleFCM_ip,ğŸ“¢ è°·æ­ŒFCM,no-resolve
  - RULE-SET,Epic_domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Origin_domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Sony_domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Steam_domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Nintendo_domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Nintendo_ip,ğŸ® æ¸¸æˆå¹³å°,no-resolve
  - RULE-SET,Netflix_domain,ğŸ¥ å¥ˆé£è§†é¢‘
  - RULE-SET,Netflix_ip,ğŸ¥ å¥ˆé£è§†é¢‘,no-resolve
  - RULE-SET,SNTP,ğŸ“º Embyå½±é™¢
  - RULE-SET,Bahamut_domain,ğŸ“º å·´å“ˆå§†ç‰¹
  - RULE-SET,Biliintl_domain,ğŸ“º å“”å“©å“”å“©
  - RULE-SET,Bilibili_domain,ğŸ“º å“”å“©å“”å“©
  - RULE-SET,Bilibili_ip,ğŸ“º å“”å“©å“”å“©,no-resolve
  - RULE-SET,ChinaMedia_domain,ğŸŒ å›½å†…åª’ä½“
  - RULE-SET,ChinaMedia_ip,ğŸŒ å›½å†…åª’ä½“,no-resolve
  - RULE-SET,IPTVMainland_domain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,GlobalMedia_domain,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,GlobalMedia_ip,ğŸŒ å›½å¤–åª’ä½“,no-resolve
  - GEOSITE,gfw,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,Download_domain,ğŸ¯ å…¨çƒç›´è¿
  - GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  Lan_domain: { <<: *domain, path: ./ruleset/Lan_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Lan/Lan_OCD_Domain.mrs"}
  Custom_Direct: { <<: *class, path: ./ruleset/Custom_Direct.list, url: "https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Direct.list"}
  Custom_Proxy: { <<: *class, path: ./ruleset/Custom_Proxy.list, url: "https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Proxy.list"}
  Direct_domain: { <<: *domain, path: ./ruleset/Direct_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Direct/Direct_OCD_Domain.mrs"}
  GoogleCNProxyIP: { <<: *class, path: ./ruleset/GoogleCNProxyIP.list, url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list"}
  Steam_CDN: { <<: *class, path: ./ruleset/Steam_CDN.list, url: "https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Steam_CDN.list"}
  Game_Download_CDN: { <<: *class, path: ./ruleset/Game_Download_CDN.list, url: "https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Game_Download_CDN.list"}

  Telegram_domain: { <<: *domain, path: ./ruleset/Telegram_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Telegram/Telegram_OCD_Domain.mrs"}
  OpenAI_domain: { <<: *domain, path: ./ruleset/OpenAI_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/OpenAI/OpenAI_OCD_Domain.mrs"}
  YouTube_domain: { <<: *domain, path: ./ruleset/YouTube_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/YouTube/YouTube_OCD_Domain.mrs"}
  Apple_domain: { <<: *domain, path: ./ruleset/Apple_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Apple/Apple_OCD_Domain.mrs"}
  Bing_domain: { <<: *domain, path: ./ruleset/Bing_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Bing/Bing_OCD_Domain.mrs"}
  OneDrive_domain: { <<: *domain, path: ./ruleset/OneDrive_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/OneDrive/OneDrive_OCD_Domain.mrs"}
  Microsoft_domain: { <<: *domain, path: ./ruleset/Microsoft_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Microsoft/Microsoft_OCD_Domain.mrs"}
  XiaoMi_domain: { <<: *domain, path: ./ruleset/XiaoMi_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/XiaoMi/XiaoMi_OCD_Domain.mrs"}
  GoogleFCM_domain: { <<: *domain, path: ./ruleset/GoogleFCM_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/GoogleFCM/GoogleFCM_OCD_Domain.mrs"}
  Epic_domain: { <<: *domain, path: ./ruleset/Epic_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Epic/Epic_OCD_Domain.mrs"}
  Origin_domain: { <<: *domain, path: ./ruleset/Origin_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Origin/Origin_OCD_Domain.mrs"}
  Sony_domain: { <<: *domain, path: ./ruleset/Sony_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Sony/Sony_OCD_Domain.mrs"}
  Steam_domain: { <<: *domain, path: ./ruleset/Steam_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Steam/Steam_OCD_Domain.mrs"}
  Nintendo_domain: { <<: *domain, path: ./ruleset/Nintendo_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Nintendo/Nintendo_OCD_Domain.mrs"}
  Netflix_domain: { <<: *domain, path: ./ruleset/Netflix_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Netflix/Netflix_OCD_Domain.mrs"}
  SNTP: { <<: *class, path: ./ruleset/SNTP.list, url: "https://raw.githubusercontent.com/Boringahhh/ssrclash/new/clash/config/SNTP.list"}
  Bahamut_domain: { <<: *domain, path: ./ruleset/Bahamut_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Bahamut/Bahamut_OCD_Domain.mrs"}
  Biliintl_domain: { <<: *domain, path: ./ruleset/Biliintl_domain.mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/biliintl.mrs"}
  Bilibili_domain: { <<: *domain, path: ./ruleset/Bilibili_domain.mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.mrs"}
  ChinaMedia_domain: { <<: *domain, path: ./ruleset/ChinaMedia_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/ChinaMedia/ChinaMedia_OCD_Domain.mrs"}
  IPTVMainland_domain: { <<: *domain, path: ./ruleset/IPTVMainland_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/IPTVMainland/IPTVMainland_OCD_Domain.mrs"}
  GlobalMedia_domain: { <<: *domain, path: ./ruleset/GlobalMedia_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/GlobalMedia/GlobalMedia_OCD_Domain.mrs"}
  Download_domain: { <<: *domain, path: ./ruleset/Download_domain.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Download/Download_OCD_Domain.mrs"}

  Lan_ip: { <<: *ip, path: ./ruleset/Lan_ip.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Lan/Lan_OCD_IP.mrs"}
  Telegram_ip: { <<: *ip, path: ./ruleset/Telegram_ip.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Telegram/Telegram_OCD_IP.mrs"}
  OpenAI_ip: { <<: *ip, path: ./ruleset/OpenAI_ip.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/OpenAI/OpenAI_OCD_IP.mrs"}
  YouTube_ip: { <<: *ip, path: ./ruleset/YouTube_ip.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/YouTube/YouTube_OCD_IP.mrs"}
  Apple_ip: { <<: *ip, path: ./ruleset/Apple_ip.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Apple/Apple_OCD_IP.mrs"}
  XiaoMi_ip: { <<: *ip, path: ./ruleset/XiaoMi_ip.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/XiaoMi/XiaoMi_OCD_IP.mrs"}
  GoogleFCM_ip: { <<: *ip, path: ./ruleset/GoogleFCM_ip.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/GoogleFCM/GoogleFCM_OCD_IP.mrs"}
  Nintendo_ip: { <<: *ip, path: ./ruleset/Nintendo_ip.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Nintendo/Nintendo_OCD_IP.mrs"}
  Netflix_ip: { <<: *ip, path: ./ruleset/Netflix_ip.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/Netflix/Netflix_OCD_IP.mrs"}
  Bilibili_ip: { <<: *ip, path: ./ruleset/Bilibili_ip.mrs, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/bilibili.mrs"}
  ChinaMedia_ip: { <<: *ip, path: ./ruleset/ChinaMedia_ip.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/ChinaMedia/ChinaMedia_OCD_IP.mrs"}
  GlobalMedia_ip: { <<: *ip, path: ./ruleset/GlobalMedia_ip.mrs, url: "https://raw.githubusercontent.com/peiyingyao/Rule-for-OCD/master/rule/Clash/GlobalMedia/GlobalMedia_OCD_IP.mrs"}
